export type PersonalRealitySectionId =
  | 'introduction'
  | 'modes'
  | 'basics'
  | 'cosmetics'
  | 'facilities'
  | 'extensions'
  | 'items'
  | 'companions'
  | 'misc'
  | 'limitations'
  | 'appendix';

export interface PersonalRealitySection {
  id: PersonalRealitySectionId;
  title: string;
  pageStart: number;
  pageEnd: number;
  summary: string;
}

export interface PersonalRealityPage {
  number: number;
  title: string;
  sectionId: PersonalRealitySectionId;
  summary: string;
}

export type PersonalRealityCoreModeId = 'upfront' | 'incremental' | 'unlimited' | 'reasonable' | 'therehouse';
export type PersonalRealityExtraModeId = 'patient-jumper' | 'swap-out' | 'cross-roads';
export type PersonalRealityOptionKind = 'toggle' | 'counter' | 'variant' | 'limitation';

export interface PersonalRealityCoreMode {
  id: PersonalRealityCoreModeId;
  title: string;
  page: number;
  summary: string;
}

export interface PersonalRealityExtraMode {
  id: PersonalRealityExtraModeId;
  title: string;
  page: number;
  summary: string;
}

export interface PersonalRealityVariant {
  id: string;
  label: string;
  costText: string;
  wpCost?: number;
  cpCost?: number;
  wpGain?: number;
  summary: string;
}

export interface PersonalRealityOption {
  id: string;
  page: number;
  title: string;
  kind: PersonalRealityOptionKind;
  description: string;
  costText: string;
  wpCost?: number;
  cpCost?: number;
  wpGain?: number;
  maxUnits?: number;
  unitLabel?: string;
  cpUnitLabel?: string;
  variants?: PersonalRealityVariant[];
  requirementsText?: string;
  requiresOptionIds?: string[];
  discountGroupId?: string;
  discountGroupLabel?: string;
  defaultSelected?: boolean;
  optionalFree?: boolean;
}

function page(number: number, title: string, sectionId: PersonalRealitySectionId, summary: string): PersonalRealityPage {
  return { number, title, sectionId, summary };
}

function coreMode(
  id: PersonalRealityCoreModeId,
  title: string,
  pageNumber: number,
  summary: string,
): PersonalRealityCoreMode {
  return { id, title, page: pageNumber, summary };
}

function extraMode(
  id: PersonalRealityExtraModeId,
  title: string,
  pageNumber: number,
  summary: string,
): PersonalRealityExtraMode {
  return { id, title, page: pageNumber, summary };
}

function option(config: PersonalRealityOption): PersonalRealityOption {
  return config;
}

export const personalRealitySections: PersonalRealitySection[] = [
  {
    id: 'introduction',
    title: 'Intro',
    pageStart: 1,
    pageEnd: 1,
    summary: 'Supplement framing, WP and CP conversion notes, and replacement compatibility.',
  },
  {
    id: 'modes',
    title: 'Modes',
    pageStart: 2,
    pageEnd: 3,
    summary: 'Core-mode budgets and optional extra-mode overlays.',
  },
  {
    id: 'basics',
    title: 'Basics',
    pageStart: 4,
    pageEnd: 16,
    summary: 'Warehouse foundations, utilities, environment, timing, and control systems.',
  },
  {
    id: 'cosmetics',
    title: 'Cosmetics',
    pageStart: 17,
    pageEnd: 19,
    summary: 'Ground cover, skies, thematics, and scenery shaping.',
  },
  {
    id: 'facilities',
    title: 'Facilities',
    pageStart: 20,
    pageEnd: 26,
    summary: 'Core rooms, housing, health systems, and shared living spaces.',
  },
  {
    id: 'extensions',
    title: 'Extensions',
    pageStart: 27,
    pageEnd: 38,
    summary: 'Dedicated workshop, leisure, storage, garage, mall, greenhouse, and menagerie add-ons.',
  },
  {
    id: 'items',
    title: 'Items',
    pageStart: 39,
    pageEnd: 40,
    summary: 'Equipment, collections, pods, and importable object support.',
  },
  {
    id: 'companions',
    title: 'Companions',
    pageStart: 41,
    pageEnd: 42,
    summary: 'Companion import clarifications and family/group import options.',
  },
  {
    id: 'misc',
    title: 'Misc',
    pageStart: 43,
    pageEnd: 47,
    summary: 'Return credits, surveillance, geometry tweaks, origin carryover, and reality-scale purchases.',
  },
  {
    id: 'limitations',
    title: 'Limitations',
    pageStart: 48,
    pageEnd: 53,
    summary: 'Permanent drawback-style limitations with duration or buyoff tracking.',
  },
  {
    id: 'appendix',
    title: 'Appendix',
    pageStart: 54,
    pageEnd: 56,
    summary: 'Changelog, synergy notes, Renegade interactions, and Therehouse clarifications.',
  },
];

export const personalRealityPages: PersonalRealityPage[] = [
  page(1, 'Introduction', 'introduction', 'Document scope, UDS note, and generic WP/CP conversion.'),
  page(2, 'Core Modes', 'modes', 'Pick one budget model for the whole supplement.'),
  page(3, 'Extra Modes', 'modes', 'Optional overlays for delayed adoption, swaps, and Crossroads play.'),
  page(4, 'Basics', 'basics', 'Warehouse freebies and second-reality basics.'),
  page(5, 'Utilities and Structures I', 'basics', 'Starting volume, storage expansion, and anti-biological safety.'),
  page(6, 'Utilities and Structures II', 'basics', 'Keys, link podiums, lofting, and underside space.'),
  page(7, 'Utilities and Structures III', 'basics', 'Portal access and portal scaling.'),
  page(8, 'Utilities and Structures IV', 'basics', 'Security alerts, force fields, and armed defenses.'),
  page(9, 'Utilities and Structures V', 'basics', 'Hospitality rules and environmental regulation.'),
  page(10, 'Utilities and Structures VI', 'basics', 'Shelving, power, energy conversion, and networking.'),
  page(11, 'Utilities and Structures VII', 'basics', 'Phones, lighting, recycling, and fabrication.'),
  page(12, 'Utilities and Structures VIII', 'basics', 'Downtime windows and baseline plumbing.'),
  page(13, 'Utilities and Structures IX', 'basics', 'Liquid hookups, barracks housing, and food baselines.'),
  page(14, 'Utilities and Structures X', 'basics', 'Food quality, sanctification, and temporal controls.'),
  page(15, 'Utilities and Structures XI', 'basics', 'Aging control, extrusion, smart control, and robots.'),
  page(16, 'Utilities and Structures XII', 'basics', 'Maintenance automation and calendar rewrites.'),
  page(17, 'Cosmetic Upgrades I', 'cosmetics', 'Skies, terrain, walls of trees, and wildlife.'),
  page(18, 'Cosmetic Upgrades II', 'cosmetics', 'Water walls, town styling, and looping space visuals.'),
  page(19, 'Cosmetic Upgrades III', 'cosmetics', 'Themes and the optional theme park.'),
  page(20, 'Facilities I', 'facilities', 'Entryways, the lounge, calibration, and the development board.'),
  page(21, 'Facilities II', 'facilities', 'Medical bay branches and body/personality pod access.'),
  page(22, 'Facilities III', 'facilities', 'Connecting doors and servant staffing.'),
  page(23, 'Facilities IV', 'facilities', 'Housing Complex baseline.'),
  page(24, 'Facilities V', 'facilities', 'Apartment quality ladders and downsizing.'),
  page(25, 'Facilities VI', 'facilities', 'Housing simulations, public areas, and the nursery.'),
  page(26, 'Facilities VII', 'facilities', 'Seraglio and grand hall space.'),
  page(27, 'Extensions I', 'extensions', 'Workshop and office extensions.'),
  page(28, 'Extensions II', 'extensions', 'Library and data services.'),
  page(29, 'Extensions III', 'extensions', 'Library collections and reproduction tools.'),
  page(30, 'Extensions IV', 'extensions', 'Classroom and training facilities.'),
  page(31, 'Extensions V', 'extensions', 'Pools, wellness, trophies, and simulators.'),
  page(32, 'Extensions VI', 'extensions', 'Entertainment and performance support.'),
  page(33, 'Extensions VII', 'extensions', 'Armory and ammunition support.'),
  page(34, 'Extensions VIII', 'extensions', 'Garden, park, and sports courts.'),
  page(35, 'Extensions IX', 'extensions', 'Games and ranged practice.'),
  page(36, 'Extensions X', 'extensions', 'Garage scaling and fueling.'),
  page(37, 'Extensions XI', 'extensions', 'Mall growth and mystery stores.'),
  page(38, 'Extensions XII', 'extensions', 'Greenhouse output and animal housing.'),
  page(39, 'Items and Equipment I', 'items', 'Cleaning, windows, computing, and music.'),
  page(40, 'Items and Equipment II', 'items', 'Passive media, pod rack rules, and art replicas.'),
  page(41, 'Companions and PR I', 'companions', 'Core companion clarification plus analogue and school imports.'),
  page(42, 'Companions and PR II', 'companions', 'Harem blocks and family-role imports.'),
  page(43, 'Miscellaneous I', 'misc', 'Return-credit economy and acceleration upgrades.'),
  page(44, 'Miscellaneous II', 'misc', 'Surveillance, recording, and geometry.'),
  page(45, 'Miscellaneous III', 'misc', 'Origin belongings and companion-owned equivalents.'),
  page(46, 'Miscellaneous IV', 'misc', 'Pre-chain recruits and galaxy-scale reality purchases.'),
  page(47, 'Miscellaneous V', 'misc', 'Dyson-shell conversion.'),
  page(48, 'Limitations I', 'limitations', 'Freeloaders, hecklers, tolls, and bat caves.'),
  page(49, 'Limitations II', 'limitations', 'Crowds, lighting, junk drift, lewdness, and hostile animals.'),
  page(50, 'Limitations III', 'limitations', 'Pests, smells, spirits, haunting, and ghost-town housing.'),
  page(51, 'Limitations IV', 'limitations', 'Time caps, tours, failing infrastructure, and breachability.'),
  page(52, 'Limitations V', 'limitations', 'Disasters, zeppelins, and labyrinth layouts.'),
  page(53, 'Limitations VI', 'limitations', 'Virtuality, entertainment-benefactor, and the woods.'),
  page(54, 'Changelog', 'appendix', 'Version history up through 1.8.'),
  page(55, 'Notes and Renegade Interactions', 'appendix', 'Synergy reminder, CP-spend list, and Renegade supplement carryover.'),
  page(56, 'Therehouse Clarifications', 'appendix', 'Real-location handling and exterior vulnerability notes.'),
];

export const personalRealityCoreModes: PersonalRealityCoreMode[] = [
  coreMode('upfront', 'Upfront Core Mode', 2, 'Start with 1500 WP and discount up to three root purchases and their upgrades.'),
  coreMode('incremental', 'Incremental Core Mode', 2, 'Start with 500 WP and gain 50 WP per completed jump or gauntlet.'),
  coreMode('unlimited', 'Unlimited Core Mode', 2, 'Start with zero WP and convert per-jump CP directly into WP.'),
  coreMode('reasonable', 'Reasonable Core Mode', 2, 'Start with 3000 WP, gain 100 WP every fifth completed jump, and cap purchases at 100 WP.'),
  coreMode('therehouse', 'Therehouse Core Mode', 2, 'Start with 5000 WP and make the reality a vulnerable in-setting physical location.'),
];

export const personalRealityExtraModes: PersonalRealityExtraMode[] = [
  extraMode('patient-jumper', 'The Patient Jumper', 3, 'Gain 100 WP for every jump after the first that you delayed taking the supplement.'),
  extraMode('swap-out', 'Swap-Out', 3, 'Retrofit an existing chain into this supplement, with an Incremental bonus when the chain is deep enough.'),
  extraMode('cross-roads', 'Cross-Roads', 3, 'Track separate collective WP earned by voluntary 100+ CP drawbacks.'),
];

export const personalRealityOptionCatalog: PersonalRealityOption[] = [
  option({
    id: 'cosmic-warehouse',
    page: 4,
    title: 'Cosmic Warehouse',
    kind: 'toggle',
    description: 'The baseline extra-dimensional storage space and integration layer.',
    costText: 'Free',
    wpCost: 0,
    defaultSelected: true,
  }),
  option({
    id: 'second-reality',
    page: 4,
    title: 'Second Reality',
    kind: 'toggle',
    description: 'A completely separate second Personal Reality with the same limitations but no budget.',
    costText: '600 WP',
    wpCost: 600,
  }),
  option({
    id: 'boxes-and-boxes',
    page: 4,
    title: 'Boxes and Boxes and Boxes',
    kind: 'toggle',
    description: 'Unlimited mundane storage containers delivered through the Box Office.',
    costText: 'Free',
    wpCost: 0,
    defaultSelected: true,
  }),
  option({
    id: 'starting-space',
    page: 5,
    title: 'Starting Space',
    kind: 'toggle',
    description: 'The baseline 80 x 80 x 10 meter interior footprint.',
    costText: 'Free',
    wpCost: 0,
    defaultSelected: true,
  }),
  option({
    id: 'additional-space',
    page: 5,
    title: 'Additional Space',
    kind: 'counter',
    description: 'Multiply the reality by ten in each standard dimension per purchase.',
    costText: '200 WP each',
    wpCost: 200,
    unitLabel: 'purchases',
    discountGroupId: 'space-expansion',
    discountGroupLabel: 'Space Expansion',
    requirementsText: 'Requires Starting Space.',
    requiresOptionIds: ['starting-space'],
  }),
  option({
    id: 'discount-additional-space',
    page: 5,
    title: 'Discount Additional Space',
    kind: 'counter',
    description: 'Multiply each dimension by three; two purchases count as one full size upgrade for linked features.',
    costText: '100 WP each',
    wpCost: 100,
    unitLabel: 'purchases',
    discountGroupId: 'space-expansion',
    requirementsText: 'Requires Starting Space.',
    requiresOptionIds: ['starting-space'],
  }),
  option({
    id: 'adaptive-inactive-storage',
    page: 5,
    title: 'Adaptive Inactive Storage',
    kind: 'toggle',
    description: 'CP purchases can rest in inactive storage until you deploy them.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Starting Space.',
    requiresOptionIds: ['starting-space'],
  }),
  option({
    id: 'antibiotic-field',
    page: 5,
    title: 'Antibiotic Field',
    kind: 'toggle',
    description: 'Normalizes microbiomes and strips harmful cross-setting contaminants between visits.',
    costText: 'Free',
    wpCost: 0,
    defaultSelected: true,
  }),
  option({
    id: 'access-key',
    page: 6,
    title: 'Access Key',
    kind: 'toggle',
    description: 'The core key-based doorway into the reality.',
    costText: 'Free',
    wpCost: 0,
    defaultSelected: true,
  }),
  option({
    id: 'additional-keys',
    page: 6,
    title: 'Additional Keys',
    kind: 'counter',
    description: 'Attuned secondary keys for trusted holders.',
    costText: '50 WP per 4 keys or 50 CP per 1 key',
    wpCost: 50,
    cpCost: 50,
    unitLabel: '4-key bundles',
    cpUnitLabel: 'single keys',
    requirementsText: 'Requires Access Key.',
    requiresOptionIds: ['access-key'],
    discountGroupId: 'access-key-group',
    discountGroupLabel: 'Access Key',
  }),
  option({
    id: 'key-link',
    page: 6,
    title: 'Key Link',
    kind: 'counter',
    description: 'Lets the entry podium re-target previously keyed host-reality doors.',
    costText: '50 WP each',
    wpCost: 50,
    unitLabel: 'podium purchases',
    requirementsText: 'Requires Access Key.',
    requiresOptionIds: ['access-key'],
    discountGroupId: 'access-key-group',
  }),
  option({
    id: 'the-big-hole',
    page: 6,
    title: 'The Big Hole',
    kind: 'toggle',
    description: 'A one-way disposal shaft into the limitless void.',
    costText: '50 WP',
    wpCost: 50,
  }),
  option({
    id: 'loft',
    page: 6,
    title: 'The Loft',
    kind: 'toggle',
    description: 'Baseline permission to stack storage up to the ceiling.',
    costText: 'Free',
    wpCost: 0,
    defaultSelected: true,
  }),
  option({
    id: 'lofty-loft',
    page: 6,
    title: 'Lofty Loft',
    kind: 'toggle',
    description: 'Dedicated non-warehouse luxury and housing space equal to the starting footprint.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires Loft.',
    requiresOptionIds: ['loft'],
    discountGroupId: 'loft-group',
    discountGroupLabel: 'Lofty Loft',
  }),
  option({
    id: 'underside',
    page: 6,
    title: 'Underside',
    kind: 'toggle',
    description: 'Basement spaces totaling up to half your Personal Reality volume.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires Lofty Loft.',
    requiresOptionIds: ['lofty-loft'],
    discountGroupId: 'loft-group',
  }),
  option({
    id: 'playing-with-portals',
    page: 7,
    title: 'Playing With Portals',
    kind: 'toggle',
    description: 'Portal-based access without relying on a keyed door.',
    costText: '300 WP',
    wpCost: 300,
    discountGroupId: 'portal-suite',
    discountGroupLabel: 'Portal Suite',
  }),
  option({
    id: 'portal-link',
    page: 7,
    title: 'Portal Link',
    kind: 'toggle',
    description: 'Lets you open exit portals from inside the Personal Reality to visited host locations.',
    costText: '300 WP',
    wpCost: 300,
    requirementsText: 'Requires Playing With Portals.',
    requiresOptionIds: ['playing-with-portals'],
    discountGroupId: 'portal-suite',
  }),
  option({
    id: 'portal-link-extra-portals',
    page: 7,
    title: 'Portal Link Additional Portals',
    kind: 'counter',
    description: 'Extra simultaneous portal capacity for Portal Link.',
    costText: '100 WP each',
    wpCost: 100,
    unitLabel: 'extra portals',
    requirementsText: 'Requires Portal Link.',
    requiresOptionIds: ['portal-link'],
    discountGroupId: 'portal-suite',
  }),
  option({
    id: 'portal-control-rod',
    page: 7,
    title: 'Portal Control Rod',
    kind: 'toggle',
    description: 'Open portals at range with a summoned pointer-like device.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Playing With Portals.',
    requiresOptionIds: ['playing-with-portals'],
    discountGroupId: 'portal-suite',
  }),
  option({
    id: 'free-portal',
    page: 7,
    title: 'Free Portal',
    kind: 'toggle',
    description: 'Remove the need for a flat physical surface and target interior areas directly.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires Playing With Portals.',
    requiresOptionIds: ['playing-with-portals'],
    discountGroupId: 'portal-suite',
  }),
  option({
    id: 'portal-aperture',
    page: 7,
    title: 'Portal Aperture',
    kind: 'counter',
    description: 'Expand portal size limits upward and downward with each purchase.',
    costText: '100 WP each',
    wpCost: 100,
    unitLabel: 'aperture upgrades',
    requirementsText: 'Requires Playing With Portals.',
    requiresOptionIds: ['playing-with-portals'],
    discountGroupId: 'portal-suite',
  }),
  option({
    id: 'security-system',
    page: 8,
    title: 'Security System',
    kind: 'toggle',
    description: 'Authorization checking and intrusion alerts at entry.',
    costText: 'Free',
    wpCost: 0,
    defaultSelected: true,
  }),
  option({
    id: 'detainment',
    page: 8,
    title: 'Detainment',
    kind: 'toggle',
    description: 'Temporary holding cells for unauthorized or actively hostile intruders.',
    costText: '300 WP',
    wpCost: 300,
    requirementsText: 'Requires Security System.',
    requiresOptionIds: ['security-system'],
    discountGroupId: 'security-suite',
    discountGroupLabel: 'Security Suite',
  }),
  option({
    id: 'security-personnel',
    page: 8,
    title: 'Security Personnel',
    kind: 'toggle',
    description: 'Reality-spanning guards with access to your tools and arsenal.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Security System and either Servants’ Quarters or Your Robots.',
    requiresOptionIds: ['security-system'],
    discountGroupId: 'security-suite',
  }),
  option({
    id: 'force-wall',
    page: 8,
    title: 'Force Wall',
    kind: 'toggle',
    description: 'Force fields over entrances that reject unauthorized traffic.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Security System.',
    requiresOptionIds: ['security-system'],
    discountGroupId: 'security-suite',
  }),
  option({
    id: 'partition-plan',
    page: 8,
    title: 'Partition Plan',
    kind: 'toggle',
    description: 'Internal force-field partitioning for zone-by-zone lockdowns.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires Force Wall.',
    requiresOptionIds: ['force-wall'],
    discountGroupId: 'security-suite',
  }),
  option({
    id: 'automated-weapons-security-system',
    page: 8,
    title: 'Automated Weapons Security System',
    kind: 'toggle',
    description: 'Automated emplacements that use your supplied weapons while handling aim, upkeep, and ammo.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Central Control.',
    requiresOptionIds: ['central-control'],
    discountGroupId: 'security-suite',
  }),
  option({
    id: 'xenia',
    page: 9,
    title: 'Xenia',
    kind: 'toggle',
    description: 'Hospitality rules that bind guests and hosts alike until someone breaks them.',
    costText: 'Optional / Free',
    wpCost: 0,
    optionalFree: true,
  }),
  option({
    id: 'environmentally-neutral',
    page: 9,
    title: 'Environmentally Neutral',
    kind: 'toggle',
    description: 'Comfortable atmosphere, breathable air, and stable gravity by default.',
    costText: 'Free',
    wpCost: 0,
    defaultSelected: true,
  }),
  option({
    id: 'environmental-controls',
    page: 9,
    title: 'Environmental Controls',
    kind: 'toggle',
    description: 'Zone-by-zone control over heat, humidity, sound, airflow, and gravity direction.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Environmentally Neutral.',
    requiresOptionIds: ['environmentally-neutral'],
    discountGroupId: 'environment-suite',
    discountGroupLabel: 'Environment Suite',
  }),
  option({
    id: 'improved-regulation',
    page: 9,
    title: 'Improved Regulation',
    kind: 'toggle',
    description: 'Extends environmental controls to extreme temperature, pressure, wind, and gravity values.',
    costText: '400 WP',
    wpCost: 400,
    requirementsText: 'Requires Environmental Controls.',
    requiresOptionIds: ['environmental-controls'],
    discountGroupId: 'environment-suite',
  }),
  option({
    id: 'shelving',
    page: 10,
    title: 'The Question of Shelving',
    kind: 'toggle',
    description: 'Industrial pallet-style shelving for the initial footprint.',
    costText: 'Free',
    wpCost: 0,
    defaultSelected: true,
  }),
  option({
    id: 'storage-solutions',
    page: 10,
    title: 'Storage Solutions',
    kind: 'toggle',
    description: 'Automatons build tailored, fiat-backed containment for anything you know how to store safely.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Shelving.',
    requiresOptionIds: ['shelving'],
  }),
  option({
    id: 'whos-got-the-powa',
    page: 10,
    title: 'Who’s Got the Powa',
    kind: 'toggle',
    description: 'Stable city-scale electrical generation and wiring.',
    costText: '100 WP',
    wpCost: 100,
    discountGroupId: 'power-suite',
    discountGroupLabel: 'Power Suite',
  }),
  option({
    id: 'power-overwhelming',
    page: 10,
    title: 'Power Overwhelming',
    kind: 'toggle',
    description: 'Dyson-sphere-scale energy output for extreme power needs.',
    costText: '400 WP',
    wpCost: 400,
    requirementsText: 'Requires Who’s Got the Powa.',
    requiresOptionIds: ['whos-got-the-powa'],
    discountGroupId: 'power-suite',
  }),
  option({
    id: 'an-intervention',
    page: 10,
    title: 'An Intervention',
    kind: 'toggle',
    description: 'Effectively unlimited reality-scale energy output.',
    costText: '800 WP',
    wpCost: 800,
    requirementsText: 'Requires Power Overwhelming.',
    requiresOptionIds: ['power-overwhelming'],
    discountGroupId: 'power-suite',
  }),
  option({
    id: 'tashi-station',
    page: 10,
    title: 'Tashi Station',
    kind: 'toggle',
    description: 'Convert electricity into setting-specific exotic energy forms.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Who’s Got the Powa.',
    requiresOptionIds: ['whos-got-the-powa'],
    discountGroupId: 'power-suite',
  }),
  option({
    id: 'digital-extranet',
    page: 10,
    title: 'Digital Extranet',
    kind: 'toggle',
    description: 'High-performance data link into the host setting’s nearest equivalent of a public network.',
    costText: '200 WP',
    wpCost: 200,
    discountGroupId: 'network-suite',
    discountGroupLabel: 'Network Suite',
  }),
  option({
    id: 'vowp-cellular-service',
    page: 11,
    title: 'Voice Over Warehouse Protocol Cellular Service',
    kind: 'toggle',
    description: 'Cross-reality phone service and handset vending with guaranteed connectivity.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Digital Extranet.',
    requiresOptionIds: ['digital-extranet'],
    discountGroupId: 'network-suite',
  }),
  option({
    id: 'neutral-lighting',
    page: 11,
    title: 'Neutral Lighting',
    kind: 'toggle',
    description: 'Ambient, source-neutral warehouse lighting.',
    costText: 'Free',
    wpCost: 0,
    defaultSelected: true,
  }),
  option({
    id: 'natural-lighting',
    page: 11,
    title: 'Natural Lighting',
    kind: 'toggle',
    description: 'Perfectly safe naturalistic light and eye-friendly illumination.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires Neutral Lighting.',
    requiresOptionIds: ['neutral-lighting'],
  }),
  option({
    id: 'recyclotron',
    page: 11,
    title: 'Recyclotron',
    kind: 'toggle',
    description: 'Breaks down waste into reusable matter and clean water.',
    costText: '200 WP',
    wpCost: 200,
    discountGroupId: 'fabrication-suite',
    discountGroupLabel: 'Fabrication Suite',
  }),
  option({
    id: 'recyclotron-capacity',
    page: 11,
    title: 'Recyclotron Capacity Upgrades',
    kind: 'counter',
    description: 'Quadruple the recycler’s throughput and storage per additional purchase.',
    costText: '50 WP each',
    wpCost: 50,
    unitLabel: 'capacity upgrades',
    requirementsText: 'Requires Recyclotron.',
    requiresOptionIds: ['recyclotron'],
    discountGroupId: 'fabrication-suite',
  }),
  option({
    id: 'fabricator',
    page: 11,
    title: 'Fabricator',
    kind: 'toggle',
    description: 'Build physical blueprinted items from recycled matter, minus metaphysical effects.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Recyclotron.',
    requiresOptionIds: ['recyclotron'],
    discountGroupId: 'fabrication-suite',
  }),
  option({
    id: 'week-and-button',
    page: 12,
    title: 'A Week & A Button',
    kind: 'toggle',
    description: 'Seven days of downtime between jumps with a manual early end.',
    costText: 'Free',
    wpCost: 0,
    defaultSelected: true,
  }),
  option({
    id: 'a-month',
    page: 12,
    title: 'A Month',
    kind: 'toggle',
    description: 'Replace the downtime week with 28 standard days.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires A Week & A Button.',
    requiresOptionIds: ['week-and-button'],
    discountGroupId: 'downtime-suite',
    discountGroupLabel: 'Downtime Suite',
  }),
  option({
    id: 'a-months-return',
    page: 12,
    title: 'A Month’s Return',
    kind: 'toggle',
    description: 'Spend inter-jump downtime revisiting prior worlds for a month.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires A Month.',
    requiresOptionIds: ['a-month'],
    discountGroupId: 'downtime-suite',
  }),
  option({
    id: 'pipes-pipes-pipes',
    page: 12,
    title: 'Pipes Pipes Pipes',
    kind: 'toggle',
    description: 'Massive plumbing, sewage, and water-distribution infrastructure for the whole reality.',
    costText: '100 WP',
    wpCost: 100,
    discountGroupId: 'water-suite',
    discountGroupLabel: 'Water Suite',
  }),
  option({
    id: 'waterworld',
    page: 12,
    title: 'Waterworld',
    kind: 'toggle',
    description: 'Planetary-scale water production with a vast hose network.',
    costText: '300 WP',
    wpCost: 300,
    requirementsText: 'Requires Pipes Pipes Pipes.',
    requiresOptionIds: ['pipes-pipes-pipes'],
    discountGroupId: 'water-suite',
  }),
  option({
    id: 'dynamic-waterworks',
    page: 13,
    title: 'Dynamic Waterworks',
    kind: 'toggle',
    description: 'Add six special liquid hook-ups sourced from user-supplied infinite feeds.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires non-supplement liquid supplies.',
    discountGroupId: 'water-suite',
  }),
  option({
    id: 'dynamic-waterworks-extra-hookups',
    page: 13,
    title: 'Dynamic Waterworks Additional Hookups',
    kind: 'counter',
    description: 'Extra sets of six custom liquid inputs.',
    costText: '50 WP per 6 or 100 CP per 1',
    wpCost: 50,
    cpCost: 100,
    unitLabel: 'six-hookup sets',
    cpUnitLabel: 'single hookups',
    requirementsText: 'Requires Dynamic Waterworks.',
    requiresOptionIds: ['dynamic-waterworks'],
    discountGroupId: 'water-suite',
  }),
  option({
    id: 'basic-accommodations',
    page: 13,
    title: 'Basic Accommodations',
    kind: 'toggle',
    description: 'Barracks-style sleeping and refugee support inside existing space.',
    costText: '50 WP',
    wpCost: 50,
    discountGroupId: 'food-and-lodging',
    discountGroupLabel: 'Food and Lodging',
  }),
  option({
    id: 'basic-nutrition',
    page: 13,
    title: 'Basic Nutrition',
    kind: 'toggle',
    description: 'Budget grocery delivery for you and companions.',
    costText: '50 WP',
    wpCost: 50,
    discountGroupId: 'food-and-lodging',
  }),
  option({
    id: 'a-little-less-basic',
    page: 13,
    title: 'A Little Less Basic',
    kind: 'toggle',
    description: 'Middle-class food budgets and broader food culture sampling.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires Basic Nutrition.',
    requiresOptionIds: ['basic-nutrition'],
    discountGroupId: 'food-and-lodging',
  }),
  option({
    id: 'a-lot-less-basic',
    page: 13,
    title: 'A Lot Less Basic',
    kind: 'toggle',
    description: 'Specific cultural food sourcing and higher weekly spending power.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires A Little Less Basic.',
    requiresOptionIds: ['a-little-less-basic'],
    discountGroupId: 'food-and-lodging',
  }),
  option({
    id: 'advanced-nutrition',
    page: 14,
    title: 'Advanced Nutrition',
    kind: 'toggle',
    description: 'Setting-spanning, highly specific food sourcing with broader quality support.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires A Lot Less Basic.',
    requiresOptionIds: ['a-lot-less-basic'],
    discountGroupId: 'food-and-lodging',
  }),
  option({
    id: 'hallowed-earth',
    page: 14,
    title: 'Hallowed Earth',
    kind: 'toggle',
    description: 'Sanctifies the entire Personal Reality and layers in awareness and holy-place bonuses.',
    costText: '400 WP',
    wpCost: 400,
  }),
  option({
    id: 'temporal-controls',
    page: 14,
    title: 'Temporal Controls',
    kind: 'toggle',
    description: 'Adjust off-screen time flow between 1:10 and 10:1.',
    costText: '200 WP',
    wpCost: 200,
    discountGroupId: 'time-suite',
    discountGroupLabel: 'Time Suite',
  }),
  option({
    id: 'stasis',
    page: 14,
    title: 'Stasis',
    kind: 'toggle',
    description: 'Freeze chambers or the whole reality in temporal stasis while you are away.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Temporal Controls.',
    requiresOptionIds: ['temporal-controls'],
    discountGroupId: 'time-suite',
  }),
  option({
    id: 'sectional-time',
    page: 14,
    title: 'Sectional Time',
    kind: 'toggle',
    description: 'Add accelerated or slowed time chambers inside the Personal Reality.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Temporal Controls.',
    requiresOptionIds: ['temporal-controls'],
    discountGroupId: 'time-suite',
  }),
  option({
    id: 'eternalizer',
    page: 15,
    title: 'Eternalizer',
    kind: 'toggle',
    description: 'Stops aging and decay for non-complex living materials and catches pest growth.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Temporal Controls.',
    requiresOptionIds: ['temporal-controls'],
    discountGroupId: 'time-suite',
  }),
  option({
    id: 'eternal-eternalizer',
    page: 15,
    title: 'Eternal Eternalizer',
    kind: 'toggle',
    description: 'Stops aging for virtually everything unless you explicitly allow it.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Eternalizer.',
    requiresOptionIds: ['eternalizer'],
    discountGroupId: 'time-suite',
  }),
  option({
    id: 'reality-extruder',
    page: 15,
    title: 'Reality Extruder',
    kind: 'toggle',
    description: 'Manifest attached structures into the current host reality with a physical linkage.',
    costText: '100 WP',
    wpCost: 100,
  }),
  option({
    id: 'central-control',
    page: 15,
    title: 'Central Control',
    kind: 'toggle',
    description: 'Pseudo-intelligent inventory, permissions, recalls, and internal door control.',
    costText: '100 WP',
    wpCost: 100,
    discountGroupId: 'control-suite',
    discountGroupLabel: 'Control Suite',
  }),
  option({
    id: 'your-robots',
    page: 15,
    title: 'Your Robots',
    kind: 'toggle',
    description: 'Sorting and retrieval robots for the Personal Reality.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Central Control.',
    requiresOptionIds: ['central-control'],
    discountGroupId: 'control-suite',
  }),
  option({
    id: 'maintenance-systems',
    page: 16,
    title: 'Maintenance Systems',
    kind: 'toggle',
    description: 'Robots expand into cleaning and repair support keyed to your own skills.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires Your Robots.',
    requiresOptionIds: ['your-robots'],
    discountGroupId: 'control-suite',
  }),
  option({
    id: 'calendar-change',
    page: 16,
    title: 'Calendar Change',
    kind: 'toggle',
    description: 'Rewrite your chain calendar and synchronize every follower to it.',
    costText: '100 WP',
    wpCost: 100,
  }),
  option({
    id: 'sky-simulator',
    page: 17,
    title: 'Sky Simulator',
    kind: 'toggle',
    description: 'Replace the ceiling with a realistic or deliberately surreal sky.',
    costText: '50 WP',
    wpCost: 50,
    discountGroupId: 'sky-ground-suite',
    discountGroupLabel: 'Sky and Ground',
  }),
  option({
    id: 'fly-a-kite',
    page: 17,
    title: 'Fly a Kite',
    kind: 'toggle',
    description: 'Make the skyspace usable for recreation and cloud play.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires Sky Simulator.',
    requiresOptionIds: ['sky-simulator'],
    discountGroupId: 'sky-ground-suite',
  }),
  option({
    id: 'realistic-ground-cover',
    page: 17,
    title: 'Realistic Ground Cover',
    kind: 'toggle',
    description: 'Replace linoleum or concrete with natural terrain, roads, or designed paths.',
    costText: '50 WP',
    wpCost: 50,
    discountGroupId: 'sky-ground-suite',
  }),
  option({
    id: 'dig-it',
    page: 17,
    title: 'Dig it',
    kind: 'toggle',
    description: 'Add deep diggable ground and proper foundations beneath supported structures.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires Realistic Ground Cover.',
    requiresOptionIds: ['realistic-ground-cover'],
    discountGroupId: 'sky-ground-suite',
  }),
  option({
    id: 'treeline-and-timber',
    page: 17,
    title: 'Treeline & Timber',
    kind: 'toggle',
    description: 'Replace walls with regrowing forest and lumber-ready treelines.',
    costText: '200 WP',
    wpCost: 200,
    discountGroupId: 'forest-suite',
    discountGroupLabel: 'Treeline & Timber',
  }),
  option({
    id: 'wildlife-for-your-wild-life',
    page: 17,
    title: 'Wildlife for Your Wild Life',
    kind: 'toggle',
    description: 'Populate the treeline with non-magical small and medium wildlife.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires Treeline & Timber.',
    requiresOptionIds: ['treeline-and-timber'],
    discountGroupId: 'forest-suite',
  }),
  option({
    id: 'the-pond',
    page: 18,
    title: 'The Pond',
    kind: 'toggle',
    description: 'Replace one wall with a water feature, shoreline, and optional marina support.',
    costText: '100 WP',
    wpCost: 100,
    discountGroupId: 'pond-suite',
    discountGroupLabel: 'The Pond',
  }),
  option({
    id: 'pond-extra-walls',
    page: 18,
    title: 'The Pond Additional Walls',
    kind: 'counter',
    description: 'Expand the pond treatment onto more Personal Reality walls.',
    costText: '50 WP each',
    wpCost: 50,
    unitLabel: 'additional walls',
    requirementsText: 'Requires The Pond.',
    requiresOptionIds: ['the-pond'],
    discountGroupId: 'pond-suite',
  }),
  option({
    id: 'the-meaning-of-life',
    page: 18,
    title: 'The Meaning of Life',
    kind: 'toggle',
    description: 'Add fish, shellfish, water plants, and mild waterfowl to the pond.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires The Pond.',
    requiresOptionIds: ['the-pond'],
    discountGroupId: 'pond-suite',
  }),
  option({
    id: 'the-village',
    page: 18,
    title: 'The Village',
    kind: 'toggle',
    description: 'Recast the Personal Reality as a townscape with aesthetic dividing paths, woods, or water.',
    costText: 'Free with required cosmetic setup',
    wpCost: 0,
    optionalFree: true,
    requirementsText: 'Requires sky and ground plus trees or pond on all four sides.',
  }),
  option({
    id: 'hollow-earth',
    page: 18,
    title: 'Hollow Earth',
    kind: 'toggle',
    description: 'Turn the interior into a cave, cylinder, or looping internal surface.',
    costText: '100 WP',
    wpCost: 100,
  }),
  option({
    id: 'basic-thematics',
    page: 19,
    title: 'Basic Thematics',
    kind: 'counter',
    description: 'Add fully sensory cosmetic themes to the Personal Reality.',
    costText: '20 WP each',
    wpCost: 20,
    unitLabel: 'themes',
    discountGroupId: 'thematics-suite',
    discountGroupLabel: 'Thematics',
  }),
  option({
    id: 'advanced-thematics',
    page: 19,
    title: 'Advanced Thematics',
    kind: 'toggle',
    description: 'Apply or dynamically adapt themes across extensions and future purchases.',
    costText: '50 WP',
    wpCost: 50,
    discountGroupId: 'thematics-suite',
  }),
  option({
    id: 'theme-park',
    page: 19,
    title: 'Theme Park',
    kind: 'variant',
    description: 'Create a jump-fed amusement park with attractions, visitors, and setting merch.',
    costText: '250 WP or 100 WP discounted',
    discountGroupId: 'theme-park',
    discountGroupLabel: 'Theme Park',
    variants: [
      {
        id: 'contained',
        label: 'Standard Placement',
        costText: '250 WP',
        wpCost: 250,
        summary: 'Adds attractions without letting the park scatter itself through the reality.',
      },
      {
        id: 'free-placement',
        label: 'Discounted Scattered Placement',
        costText: '100 WP',
        wpCost: 100,
        summary: 'Take the 150 WP discount and let the park establish venues where it wants.',
      },
    ],
  }),
  option({
    id: 'entrance-hall',
    page: 20,
    title: 'Entrance Hall',
    kind: 'toggle',
    description: 'The base white-walled arrival room keyed to outside access.',
    costText: 'First free',
    wpCost: 0,
    defaultSelected: true,
    discountGroupId: 'entrance-hall-group',
    discountGroupLabel: 'Entrance Hall',
  }),
  option({
    id: 'additional-entrance-halls',
    page: 20,
    title: 'Additional Entrance Halls',
    kind: 'counter',
    description: 'Specialized extra entry halls that can be restricted to certain keys or zones.',
    costText: '20 WP each',
    wpCost: 20,
    unitLabel: 'extra halls',
    requirementsText: 'Uses the Entrance Hall base feature.',
    discountGroupId: 'entrance-hall-group',
  }),
  option({
    id: 'benefactor-lounge',
    page: 20,
    title: 'The Benefactor Lounge',
    kind: 'toggle',
    description: 'A shifting meeting room for build conversations and notes to your Benefactor.',
    costText: 'Optional but Free',
    wpCost: 0,
    optionalFree: true,
  }),
  option({
    id: 'companion-calibration-unit',
    page: 20,
    title: 'Companion Calibration Unit',
    kind: 'toggle',
    description: 'Baseline diagnostic and restorative scan cabinet for companions and comparable targets.',
    costText: '10 WP',
    wpCost: 10,
  }),
  option({
    id: 'reality-development-board',
    page: 20,
    title: 'The Reality Development Board',
    kind: 'toggle',
    description: 'A construction, planning, moving, and installation team for Personal Reality projects.',
    costText: '200 WP',
    wpCost: 200,
  }),
  option({
    id: 'medical-bay',
    page: 21,
    title: 'The Medical Bay',
    kind: 'toggle',
    description: 'Treats most medical and dental issues short of advanced augmentation or defect repair.',
    costText: '100 WP',
    wpCost: 100,
    discountGroupId: 'medical-suite',
    discountGroupLabel: 'Medical Bay',
  }),
  option({
    id: 'the-better-bay',
    page: 21,
    title: 'The Better Bay',
    kind: 'toggle',
    description: 'Faster, cleaner healing and revival while the brain still functions.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires the Medical Bay.',
    requiresOptionIds: ['medical-bay'],
    discountGroupId: 'medical-suite',
  }),
  option({
    id: 'counseling-bay',
    page: 21,
    title: 'The Counseling Bay',
    kind: 'toggle',
    description: 'Long-form psychological treatment and therapy support.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Medical Bay.',
    requiresOptionIds: ['medical-bay'],
    discountGroupId: 'medical-suite',
  }),
  option({
    id: 'cybernetics-bay',
    page: 21,
    title: 'The Cybernetics Bay',
    kind: 'toggle',
    description: 'Repair and replace cybernetic or biomedical implants with fiat backing for in-bay installs.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Medical Bay and a Cybernetic Workshop.',
    requiresOptionIds: ['medical-bay'],
    discountGroupId: 'medical-suite',
  }),
  option({
    id: 'nano-medical-lab',
    page: 21,
    title: 'The Nano-Medical Lab',
    kind: 'toggle',
    description: 'Analyze, remove, replicate, and administer nanotech contamination or support.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires Medical Bay.',
    requiresOptionIds: ['medical-bay'],
    discountGroupId: 'medical-suite',
  }),
  option({
    id: 'bio-synthesis-lab',
    page: 21,
    title: 'The Bio-Synthesis Lab',
    kind: 'toggle',
    description: 'Handles serums, viruses, bacteria, and retroviral repair or enhancement science.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires Medical Bay.',
    requiresOptionIds: ['medical-bay'],
    discountGroupId: 'medical-suite',
  }),
  option({
    id: 'microbiome-replacement-lab',
    page: 21,
    title: 'The Microbiome Replacement Lab',
    kind: 'toggle',
    description: 'Build benign replacement microbiomes, viromes, and similar symbiotes.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires Bio-Synthesis Lab.',
    requiresOptionIds: ['bio-synthesis-lab'],
    discountGroupId: 'medical-suite',
  }),
  option({
    id: 'personal-mod-pods',
    page: 21,
    title: 'Personal Mod Pods',
    kind: 'counter',
    description: 'Give non-jumpers access to your body or personality mod setup once each.',
    costText: '100 WP first purchase, then 20 WP to double pod count',
    wpCost: 100,
    unitLabel: 'pod purchases',
    discountGroupId: 'personal-mod-pods',
    discountGroupLabel: 'Personal Mod Pods',
  }),
  option({
    id: 'connecting-doors',
    page: 22,
    title: 'Connecting Doors',
    kind: 'counter',
    description: 'Personal-Reality-only door pairs that double in quantity each purchase.',
    costText: '20 WP per purchase',
    wpCost: 20,
    unitLabel: 'purchases',
    discountGroupId: 'door-suite',
    discountGroupLabel: 'Connecting Doors',
  }),
  option({
    id: 'inter-reality-connecting-doors',
    page: 22,
    title: 'Inter-Reality Connecting Doors',
    kind: 'counter',
    description: 'Door pairs linking a Personal Reality location to a fixed external place.',
    costText: '50 WP per pair',
    wpCost: 50,
    unitLabel: 'pairs',
    discountGroupId: 'door-suite',
  }),
  option({
    id: 'high-security-inter-reality-connecting-doors',
    page: 22,
    title: 'High Security Inter-Reality Connecting Doors',
    kind: 'counter',
    description: 'Lockable, force-wall-compatible inter-reality door pairs with free breakage.',
    costText: '200 WP per pair',
    wpCost: 200,
    unitLabel: 'pairs',
    discountGroupId: 'door-suite',
  }),
  option({
    id: 'servants-quarters',
    page: 22,
    title: 'Servants’ Quarters',
    kind: 'toggle',
    description: 'Loyal, immortal household staff sized to your retinue.',
    costText: '100 WP',
    wpCost: 100,
    discountGroupId: 'servant-suite',
    discountGroupLabel: 'Servants’ Quarters',
  }),
  option({
    id: 'unique-servants',
    page: 22,
    title: 'Unique Servants',
    kind: 'toggle',
    description: 'Reskin the servants into robots, elves, zombies, homunculi, and similar themes.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires Servants’ Quarters.',
    requiresOptionIds: ['servants-quarters'],
    discountGroupId: 'servant-suite',
  }),
  option({
    id: 'housing-complex',
    page: 23,
    title: 'Housing Complex',
    kind: 'toggle',
    description: 'Sapient retinue housing with apartment-style growth and default shared rooms.',
    costText: '100 WP',
    wpCost: 100,
    discountGroupId: 'housing-complex',
    discountGroupLabel: 'Housing Complex',
  }),
  option({
    id: 'rooms-for-cheap',
    page: 24,
    title: 'Rooms for Cheap',
    kind: 'counter',
    description: 'Add more rooms to the housing stock in broad batches.',
    costText: '10 WP each',
    wpCost: 10,
    unitLabel: 'room expansions',
    requirementsText: 'Requires Housing Complex.',
    requiresOptionIds: ['housing-complex'],
    discountGroupId: 'housing-complex',
  }),
  option({
    id: 'choice-apartments',
    page: 24,
    title: 'Choice Apartments',
    kind: 'counter',
    description: 'Upgrade one third of basic units per purchase into better-finished housing.',
    costText: '10 WP or 200 CP each',
    wpCost: 10,
    cpCost: 200,
    unitLabel: 'upgrades',
    cpUnitLabel: 'CP upgrades',
    maxUnits: 3,
    requirementsText: 'Requires Housing Complex.',
    requiresOptionIds: ['housing-complex'],
    discountGroupId: 'housing-complex',
  }),
  option({
    id: 'luxury-apartments',
    page: 24,
    title: 'Luxury Apartments',
    kind: 'counter',
    description: 'Upgrade one tenth of Choice units per purchase into larger, soundproof luxury suites.',
    costText: '10 WP or 200 CP each',
    wpCost: 10,
    cpCost: 200,
    unitLabel: 'upgrades',
    cpUnitLabel: 'CP upgrades',
    maxUnits: 10,
    requirementsText: 'Requires Choice Apartments.',
    requiresOptionIds: ['choice-apartments'],
    discountGroupId: 'housing-complex',
  }),
  option({
    id: 'opulent-apartments',
    page: 24,
    title: 'Opulent Apartments',
    kind: 'counter',
    description: 'Upgrade one tenth of Luxury units per purchase into extravagant, oversized suites.',
    costText: '20 WP or 400 CP each',
    wpCost: 20,
    cpCost: 400,
    unitLabel: 'upgrades',
    cpUnitLabel: 'CP upgrades',
    maxUnits: 10,
    requirementsText: 'Requires Luxury Apartments.',
    requiresOptionIds: ['luxury-apartments'],
    discountGroupId: 'housing-complex',
  }),
  option({
    id: 'downsizing',
    page: 24,
    title: 'Downsizing',
    kind: 'counter',
    description: 'Shrink building cluster size, eventually turning apartments into standalone houses.',
    costText: '10 WP or 200 CP each',
    wpCost: 10,
    cpCost: 200,
    unitLabel: 'downsizing steps',
    cpUnitLabel: 'CP steps',
    maxUnits: 5,
    requirementsText: 'Requires Housing Complex.',
    requiresOptionIds: ['housing-complex'],
    discountGroupId: 'housing-complex',
  }),
  option({
    id: 'upscaling',
    page: 25,
    title: 'Upscaling',
    kind: 'counter',
    description: 'Buy housing-only environmental simulations and zone variants in bundles of three effects.',
    costText: '5 WP or 100 CP each',
    wpCost: 5,
    cpCost: 100,
    unitLabel: 'simulation purchases',
    cpUnitLabel: 'CP purchases',
    requirementsText: 'Requires Housing Complex.',
    requiresOptionIds: ['housing-complex'],
    discountGroupId: 'housing-complex',
  }),
  option({
    id: 'the-commons',
    page: 25,
    title: 'The Commons',
    kind: 'toggle',
    description: 'Community indoor social hub with kitchen and stage.',
    costText: '30 WP or 600 CP',
    wpCost: 30,
    cpCost: 600,
    requirementsText: 'Requires at least 1 purchase of Choice Apartments.',
    requiresOptionIds: ['choice-apartments'],
    discountGroupId: 'housing-complex',
  }),
  option({
    id: 'the-quadrangle',
    page: 25,
    title: 'The Quadrangle',
    kind: 'toggle',
    description: 'Large external parkland with built-in weather and foliage cycles.',
    costText: '40 WP or 800 CP',
    wpCost: 40,
    cpCost: 800,
    requirementsText: 'Requires at least 2 purchases of Luxury Apartments.',
    requiresOptionIds: ['luxury-apartments'],
    discountGroupId: 'housing-complex',
  }),
  option({
    id: 'the-esplanade',
    page: 25,
    title: 'The Esplanade',
    kind: 'toggle',
    description: 'A boardwalk-and-canal commercial public frontage around the whole complex.',
    costText: '50 WP or 1000 CP',
    wpCost: 50,
    cpCost: 1000,
    requirementsText: 'Requires at least 4 purchases of Opulent Apartments.',
    requiresOptionIds: ['opulent-apartments'],
    discountGroupId: 'housing-complex',
  }),
  option({
    id: 'a-stellar-nursery',
    page: 25,
    title: 'A Stellar Nursery',
    kind: 'toggle',
    description: 'Infant and toddler care infrastructure with uterine replicators and adapted support systems.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires Medical Bay or Housing Complex.',
    discountGroupId: 'housing-complex',
  }),
  option({
    id: 'seraglio-a-gogo',
    page: 26,
    title: 'Seraglio-A-Gogo',
    kind: 'toggle',
    description: 'A scented courtyard retreat with compressed relaxation time.',
    costText: '200 WP',
    wpCost: 200,
  }),
  option({
    id: 'grand-dining-hall',
    page: 26,
    title: 'Grand Dining Hall',
    kind: 'toggle',
    description: 'A celebratory hall that scales with your followers and draws from your food purchases.',
    costText: '100 WP',
    wpCost: 100,
  }),
  option({
    id: 'workshop-row',
    page: 27,
    title: 'Workshop Row',
    kind: 'counter',
    description: 'Add a specialized workshop or expand an existing one.',
    costText: '100 WP each',
    wpCost: 100,
    unitLabel: 'workshops',
    discountGroupId: 'workshop-row',
    discountGroupLabel: 'Workshop Row',
  }),
  option({
    id: 'infinite-office-worx',
    page: 27,
    title: 'Infinite Office Worx',
    kind: 'counter',
    description: 'Personal offices or cubicle farms with focus and comprehension bonuses.',
    costText: '10 WP or 50 CP each',
    wpCost: 10,
    cpCost: 50,
    unitLabel: 'office purchases',
    cpUnitLabel: 'CP purchases',
  }),
  option({
    id: 'library-jumpxandria',
    page: 28,
    title: 'The Library Jumpxandria',
    kind: 'toggle',
    description: 'Pristine storage, sorting, and reading space for gathered texts.',
    costText: '100 WP',
    wpCost: 100,
    discountGroupId: 'library-suite',
    discountGroupLabel: 'Library Jumpxandria',
  }),
  option({
    id: 'library-services',
    page: 28,
    title: 'Library Services',
    kind: 'toggle',
    description: 'Appendices, scholarship notes, and translation-on-request for library works.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires The Library Jumpxandria.',
    requiresOptionIds: ['library-jumpxandria'],
    discountGroupId: 'library-suite',
  }),
  option({
    id: 'digital-database',
    page: 28,
    title: 'Digital Database',
    kind: 'toggle',
    description: 'Digitize, sanitize, search, and cross-reference all library texts.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires The Library Jumpxandria and Central Control.',
    requiresOptionIds: ['library-jumpxandria', 'central-control'],
    discountGroupId: 'library-suite',
  }),
  option({
    id: 'starting-collection',
    page: 29,
    title: 'Starting Collection',
    kind: 'counter',
    description: 'Seed the library with town-and-school scale fiction, non-fiction, and periodicals.',
    costText: '100 WP first purchase, 50 WP additional purchases',
    wpCost: 100,
    maxUnits: 5,
    unitLabel: 'collection tiers',
    requirementsText: 'Requires The Library Jumpxandria.',
    requiresOptionIds: ['library-jumpxandria'],
    discountGroupId: 'library-suite',
  }),
  option({
    id: 'expanded-collection',
    page: 29,
    title: 'Expanded Collection',
    kind: 'counter',
    description: 'Add a real-world specialized subject library and monthly topic requests.',
    costText: '50 WP or 150 CP each',
    wpCost: 50,
    cpCost: 150,
    unitLabel: 'subject packs',
    cpUnitLabel: 'CP subject packs',
    requirementsText: 'Requires The Library Jumpxandria.',
    requiresOptionIds: ['library-jumpxandria'],
    discountGroupId: 'library-suite',
  }),
  option({
    id: 'esoteric-collection',
    page: 29,
    title: 'Esoteric Collection',
    kind: 'counter',
    description: 'Expanded Collection for subjects known in visited settings, including fiction from them.',
    costText: '100 WP or 500 CP each',
    wpCost: 100,
    cpCost: 500,
    unitLabel: 'subject packs',
    cpUnitLabel: 'CP subject packs',
    requirementsText: 'Requires The Library Jumpxandria.',
    requiresOptionIds: ['library-jumpxandria'],
    discountGroupId: 'library-suite',
  }),
  option({
    id: 'printing-precious',
    page: 29,
    title: 'Printing Precious',
    kind: 'toggle',
    description: 'Perfectly forge mundane cultural relics, texts, and facsimiles from sufficient references.',
    costText: '150 WP',
    wpCost: 150,
    requirementsText: 'Requires The Library Jumpxandria and Fabricator.',
    requiresOptionIds: ['library-jumpxandria', 'fabricator'],
    discountGroupId: 'library-suite',
  }),
  option({
    id: 'printing-precious-extra-machines',
    page: 29,
    title: 'Printing Precious Additional Machines',
    kind: 'counter',
    description: 'Add more duplication machines to increase throughput.',
    costText: '20 WP or 300 CP each',
    wpCost: 20,
    cpCost: 300,
    unitLabel: 'extra machines',
    cpUnitLabel: 'CP machines',
    requirementsText: 'Requires Printing Precious.',
    requiresOptionIds: ['printing-precious'],
    discountGroupId: 'library-suite',
  }),
  option({
    id: 'a-classy-classroom',
    page: 30,
    title: 'A Classy Classroom',
    kind: 'toggle',
    description: 'A teaching room that updates with relevant support gear and gives mild teaching/learning boosts.',
    costText: '10 WP',
    wpCost: 10,
    discountGroupId: 'training-suite',
    discountGroupLabel: 'Training Suite',
  }),
  option({
    id: 'gym-nice-ium',
    page: 30,
    title: 'Gym-Nice-Ium',
    kind: 'toggle',
    description: 'Exercise and sparring space with safer training and med-bay routing.',
    costText: '100 WP',
    wpCost: 100,
    discountGroupId: 'training-suite',
  }),
  option({
    id: 'gym-nasty-um',
    page: 30,
    title: 'Gym-Nasty-Um',
    kind: 'toggle',
    description: 'Arena-grade duplodroid training with nonfatal replay and limited-use technique rehearsal.',
    costText: '300 WP',
    wpCost: 300,
    requirementsText: 'Requires Gym-Nice-Ium and Your Robots.',
    requiresOptionIds: ['gym-nice-ium', 'your-robots'],
    discountGroupId: 'training-suite',
  }),
  option({
    id: 'gym-classy-um',
    page: 30,
    title: 'Gym-Classy-Um',
    kind: 'toggle',
    description: 'Extend arena training into mental and spiritual potential with daily energy refresh.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Gym-Nasty-Um and Classroom.',
    requiresOptionIds: ['gym-nasty-um', 'a-classy-classroom'],
    discountGroupId: 'training-suite',
  }),
  option({
    id: 'the-big-pool',
    page: 31,
    title: 'The Big Pool',
    kind: 'toggle',
    description: 'An Olympic water park complex with automatic tech upgrades.',
    costText: '10 WP',
    wpCost: 10,
    requirementsText: 'Requires Pipes Pipes Pipes.',
    requiresOptionIds: ['pipes-pipes-pipes'],
    discountGroupId: 'pool-suite',
    discountGroupLabel: 'The Big Pool',
  }),
  option({
    id: 'the-bigger-pool',
    page: 31,
    title: 'The Bigger Pool',
    kind: 'toggle',
    description: 'Add a lazy river and indoor beach complex to the pool zone.',
    costText: '20 WP',
    wpCost: 20,
    requirementsText: 'Requires The Big Pool.',
    requiresOptionIds: ['the-big-pool'],
    discountGroupId: 'pool-suite',
  }),
  option({
    id: 'lets-have-fun',
    page: 31,
    title: 'Let’s Have Fun',
    kind: 'toggle',
    description: 'Add slides, waterfalls, waves, coves, and massage pools.',
    costText: '30 WP',
    wpCost: 30,
    requirementsText: 'Requires The Big Pool.',
    requiresOptionIds: ['the-big-pool'],
    discountGroupId: 'pool-suite',
  }),
  option({
    id: 'wellness-centre',
    page: 31,
    title: 'Wellness Centre',
    kind: 'toggle',
    description: 'Massage and spa complex for you, companions, and hangers-on.',
    costText: '50 WP',
    wpCost: 50,
    discountGroupId: 'wellness-suite',
    discountGroupLabel: 'Wellness Centre',
  }),
  option({
    id: 'baf-and-booty-works',
    page: 31,
    title: 'Baf and Booty Works',
    kind: 'toggle',
    description: 'Roman, Japanese, and Chinese style bathing complexes with sauna support.',
    costText: '20 WP',
    wpCost: 20,
    requirementsText: 'Requires Wellness Centre.',
    requiresOptionIds: ['wellness-centre'],
    discountGroupId: 'wellness-suite',
  }),
  option({
    id: 'trophy-room',
    page: 31,
    title: 'A Room For Your Trophies and Cigars',
    kind: 'toggle',
    description: 'Display chamber that preserves trophies, awards, and memorabilia safely.',
    costText: '10 WP',
    wpCost: 10,
  }),
  option({
    id: 'pilot-simulator',
    page: 31,
    title: 'Pilot Simulator',
    kind: 'toggle',
    description: 'Vehicle operation simulator with linked bays and license training.',
    costText: '50 WP',
    wpCost: 50,
  }),
  option({
    id: 'entertainment-room',
    page: 32,
    title: 'Entertainment Room',
    kind: 'toggle',
    description: 'Six-room theatre, music, gaming, and stage complex.',
    costText: '50 WP',
    wpCost: 50,
    discountGroupId: 'entertainment-suite',
    discountGroupLabel: 'Entertainment Room',
  }),
  option({
    id: 'kit-and-kaboodle',
    page: 32,
    title: 'Kit and Kaboodle',
    kind: 'toggle',
    description: 'Add instruments, recording gear, and mixing support to the entertainment suite.',
    costText: '20 WP',
    wpCost: 20,
    requirementsText: 'Requires Entertainment Room.',
    requiresOptionIds: ['entertainment-room'],
    discountGroupId: 'entertainment-suite',
  }),
  option({
    id: 'the-audacious-auditorium',
    page: 32,
    title: 'The Audacious Auditorium',
    kind: 'toggle',
    description: 'A larger auditorium with built-in technical support for productions.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires Entertainment Room and Housing Complex.',
    requiresOptionIds: ['entertainment-room', 'housing-complex'],
    discountGroupId: 'entertainment-suite',
  }),
  option({
    id: 'costume-closet',
    page: 32,
    title: 'Costume Closet',
    kind: 'toggle',
    description: 'Self-cleaning costumes fitted for performance needs.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires Entertainment Room.',
    requiresOptionIds: ['entertainment-room'],
    discountGroupId: 'entertainment-suite',
  }),
  option({
    id: 'propshop-and-scenery',
    page: 32,
    title: 'Propshop & Scenery',
    kind: 'toggle',
    description: 'Foam, paint, wood, and stage-quality set fabrication for performances.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires Entertainment Room and Workshop Row.',
    requiresOptionIds: ['entertainment-room', 'workshop-row'],
    discountGroupId: 'entertainment-suite',
  }),
  option({
    id: 'watch-your-arsenal',
    page: 33,
    title: 'Watch Your Arsenal',
    kind: 'toggle',
    description: 'Distributed armory space with cleaning, repair, and childproofing support.',
    costText: '200 WP',
    wpCost: 200,
    discountGroupId: 'arsenal-suite',
    discountGroupLabel: 'Watch Your Arsenal',
  }),
  option({
    id: 'ammo-dumpty-dump',
    page: 33,
    title: 'Ammo Dumpty-Dump',
    kind: 'toggle',
    description: 'Restock ships, guns, and mecha with scalable ammunition production.',
    costText: '300 WP',
    wpCost: 300,
    requirementsText: 'Requires Watch Your Arsenal and The Garage of the Gods.',
    requiresOptionIds: ['watch-your-arsenal', 'the-garage-of-the-gods'],
    discountGroupId: 'arsenal-suite',
  }),
  option({
    id: 'semi-secret-garden',
    page: 34,
    title: 'The Semi-Secret Garden',
    kind: 'toggle',
    description: 'A large aesthetic garden with benches, fountains, and pleasant ambience.',
    costText: '50 WP',
    wpCost: 50,
    discountGroupId: 'garden-suite',
    discountGroupLabel: 'Semi-Secret Garden',
  }),
  option({
    id: 'parkland-paradise',
    page: 34,
    title: 'Parkland Paradise',
    kind: 'toggle',
    description: 'Expand the garden into a much larger park with running and skating paths.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires The Semi-Secret Garden.',
    requiresOptionIds: ['semi-secret-garden'],
    discountGroupId: 'garden-suite',
  }),
  option({
    id: 'meditation-corners',
    page: 34,
    title: 'Meditatiation Corners',
    kind: 'toggle',
    description: 'Protected meditation alcoves where time spent meditating is quadrupled.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires The Semi-Secret Garden.',
    requiresOptionIds: ['semi-secret-garden'],
    discountGroupId: 'garden-suite',
  }),
  option({
    id: 'high-courts-and-low',
    page: 34,
    title: 'High Courts & Low',
    kind: 'toggle',
    description: 'Add courts, pitches, and prepared sport surfaces to the garden or quadrangles.',
    costText: '10 WP',
    wpCost: 10,
    requirementsText: 'Requires The Semi-Secret Garden.',
    requiresOptionIds: ['semi-secret-garden'],
    discountGroupId: 'garden-suite',
  }),
  option({
    id: 'im-game-room',
    page: 35,
    title: 'I’m Game Room',
    kind: 'toggle',
    description: 'LAN-ready PCs, consoles, arcade machines, tables, and a drip-fed game library.',
    costText: '100 WP',
    wpCost: 100,
  }),
  option({
    id: 'a-range-of-ranges',
    page: 35,
    title: 'A Range of Ranges',
    kind: 'toggle',
    description: 'Harmless but accurate ranged-weapon practice, with optional larger arenas.',
    costText: '50 WP',
    wpCost: 50,
  }),
  option({
    id: 'the-garage-of-the-gods',
    page: 36,
    title: 'The Garage of the Gods',
    kind: 'toggle',
    description: 'Vehicle garage with berths, vehicular entry halls, and portal adaptors.',
    costText: '200 WP',
    wpCost: 200,
    discountGroupId: 'garage-suite',
    discountGroupLabel: 'Garage of the Gods',
  }),
  option({
    id: 'wide-berth-expansion',
    page: 36,
    title: 'Wide Berth Expansion',
    kind: 'counter',
    description: 'Double berth dimensions with each purchase.',
    costText: '20 WP or 100 CP each',
    wpCost: 20,
    cpCost: 100,
    unitLabel: 'size upgrades',
    cpUnitLabel: 'CP size upgrades',
    requirementsText: 'Requires The Garage of the Gods.',
    requiresOptionIds: ['the-garage-of-the-gods'],
    discountGroupId: 'garage-suite',
  }),
  option({
    id: 'getcha-berths-here-boyo',
    page: 36,
    title: 'Getcha Berths Here, Boyo!',
    kind: 'counter',
    description: 'Add more standard berths to the garage.',
    costText: '20 WP or 100 CP each',
    wpCost: 20,
    cpCost: 100,
    unitLabel: 'berth packs',
    cpUnitLabel: 'CP berth packs',
    requirementsText: 'Requires The Garage of the Gods.',
    requiresOptionIds: ['the-garage-of-the-gods'],
    discountGroupId: 'garage-suite',
  }),
  option({
    id: 'adaptor-adaptation',
    page: 36,
    title: 'Adaptor Adaptation',
    kind: 'counter',
    description: 'Add more vehicle portal adaptors per VEH each jump.',
    costText: '10 WP each',
    wpCost: 10,
    unitLabel: 'adaptor batches',
    requirementsText: 'Requires The Garage of the Gods.',
    requiresOptionIds: ['the-garage-of-the-gods'],
    discountGroupId: 'garage-suite',
  }),
  option({
    id: 'fueling-station',
    page: 36,
    title: 'Fueling Station',
    kind: 'toggle',
    description: 'Supply mundane vehicle fuels that evaporate if removed.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires The Garage of the Gods.',
    requiresOptionIds: ['the-garage-of-the-gods'],
    discountGroupId: 'garage-suite',
  }),
  option({
    id: 'eldritch-fueling-station',
    page: 36,
    title: 'Eldritch Fueling Station',
    kind: 'toggle',
    description: 'Fuel even esoteric or magical vehicles.',
    costText: '150 WP',
    wpCost: 150,
    requirementsText: 'Requires Fueling Station.',
    requiresOptionIds: ['fueling-station'],
    discountGroupId: 'garage-suite',
  }),
  option({
    id: 'the-big-garage',
    page: 36,
    title: 'The Big Garage',
    kind: 'toggle',
    description: 'Four effectively unbounded dry docks for truly massive craft.',
    costText: '300 WP',
    wpCost: 300,
    requirementsText: 'Requires The Garage of the Gods.',
    requiresOptionIds: ['the-garage-of-the-gods'],
    discountGroupId: 'garage-suite',
  }),
  option({
    id: 'the-titans-mall',
    page: 37,
    title: 'The Titan’s Mall',
    kind: 'toggle',
    description: 'A 15-shop mall sourcing goods from the current host reality.',
    costText: '100 WP',
    wpCost: 100,
    discountGroupId: 'mall-suite',
    discountGroupLabel: 'Titan’s Mall',
  }),
  option({
    id: 'more-for-more',
    page: 37,
    title: 'More for More',
    kind: 'counter',
    description: 'Upgrade shop quality or add lower-tier stores in larger numbers.',
    costText: '50 WP each',
    wpCost: 50,
    unitLabel: 'mall upgrades',
    requirementsText: 'Requires The Titan’s Mall.',
    requiresOptionIds: ['the-titans-mall'],
    discountGroupId: 'mall-suite',
  }),
  option({
    id: 'mall-of-all',
    page: 37,
    title: 'Mall of All',
    kind: 'counter',
    description: 'Double the mall after reaching 65 shops and add restaurant packages each time.',
    costText: '100 WP each',
    wpCost: 100,
    unitLabel: 'mall doublings',
    requirementsText: 'Requires More for More and a 65-shop mall.',
    requiresOptionIds: ['more-for-more'],
    discountGroupId: 'mall-suite',
  }),
  option({
    id: 'jump-topic',
    page: 37,
    title: 'Jump Topic',
    kind: 'toggle',
    description: 'Add one host-setting-specific consumer-goods store after each jump.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires The Titan’s Mall.',
    requiresOptionIds: ['the-titans-mall'],
    discountGroupId: 'mall-suite',
  }),
  option({
    id: 'the-mall-of-mystery',
    page: 37,
    title: 'The Mall of Mystery',
    kind: 'toggle',
    description: 'Manifest shifting specialty stores and a larger, stranger, monster-prone mall layout.',
    costText: '200 WP',
    wpCost: 200,
    requirementsText: 'Requires Mall of All and Jump Topic.',
    requiresOptionIds: ['mall-of-all', 'jump-topic'],
    discountGroupId: 'mall-suite',
  }),
  option({
    id: 'guardians-greenhouse',
    page: 38,
    title: 'Guardian’s Greenhouse',
    kind: 'toggle',
    description: 'Large-scale greenhouse with analyzers, chillers, and high-quality output guarantees.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires Pipes Pipes Pipes and either Natural Lighting or Who’s Got The Powa.',
    requiresOptionIds: ['pipes-pipes-pipes'],
    discountGroupId: 'greenhouse-suite',
    discountGroupLabel: 'Guardian’s Greenhouse',
  }),
  option({
    id: 'seeds-and-seedlings',
    page: 38,
    title: 'Seeds and Seedlings',
    kind: 'counter',
    description: 'Yearly seed and seedling packages from visited settings.',
    costText: '50 WP each',
    wpCost: 50,
    unitLabel: 'seed programs',
    requirementsText: 'Requires Guardian’s Greenhouse.',
    requiresOptionIds: ['guardians-greenhouse'],
    discountGroupId: 'greenhouse-suite',
  }),
  option({
    id: 'the-mystical-menagerie',
    page: 38,
    title: 'The Mystical Menagerie',
    kind: 'toggle',
    description: 'Dedicated, large-scale animal habitats with feed, drink, and environment matching.',
    costText: '200 WP',
    wpCost: 200,
  }),
  option({
    id: 'cleaning-supplies',
    page: 39,
    title: 'Cleaning Supplies',
    kind: 'toggle',
    description: 'Infinite harmless cleaning supplies tuned to Personal Reality upkeep.',
    costText: 'Free',
    wpCost: 0,
    defaultSelected: true,
  }),
  option({
    id: 'windows',
    page: 39,
    title: 'Windows',
    kind: 'toggle',
    description: 'Install windows with scenery views from the current jump.',
    costText: '50 WP',
    wpCost: 50,
    discountGroupId: 'windows-suite',
    discountGroupLabel: 'Windows',
  }),
  option({
    id: 'windows-of-nostalgia',
    page: 39,
    title: 'Windows of Nostalgia',
    kind: 'toggle',
    description: 'Let windows show scenes from previous jumps.',
    costText: '50 WP',
    wpCost: 50,
    requirementsText: 'Requires Windows.',
    requiresOptionIds: ['windows'],
    discountGroupId: 'windows-suite',
  }),
  option({
    id: 'computer-hub',
    page: 39,
    title: 'Computer Hub',
    kind: 'toggle',
    description: 'Top-end mainframe, printers, scanners, and personal computing devices for you and companions.',
    costText: '50 WP',
    wpCost: 50,
  }),
  option({
    id: 'music-collection',
    page: 39,
    title: 'Music Collection',
    kind: 'counter',
    description: '500-album curated collections with commentary, covers, and replacements for misses.',
    costText: '20 WP each',
    wpCost: 20,
    unitLabel: 'collections',
  }),
  option({
    id: 'movie-tv-series-collection',
    page: 40,
    title: 'Movie & TV Series Collection',
    kind: 'toggle',
    description: '15,000 hours of visual media with subtitles, commentary, and dubbed audio.',
    costText: '50 WP',
    wpCost: 50,
  }),
  option({
    id: 'pod-rack',
    page: 40,
    title: 'Pod Rack',
    kind: 'counter',
    description: 'Pod storage for bringing unwilling or willing non-companions along.',
    costText: '200 WP for the rack and first pod, 50 WP per additional pod',
    wpCost: 200,
    unitLabel: 'pods',
    discountGroupId: 'pod-rack',
    discountGroupLabel: 'Pod Rack',
  }),
  option({
    id: 'pod-override-exclusion',
    page: 40,
    title: 'Pod Override Exclusion',
    kind: 'toggle',
    description: 'Keep podded people as podded cargo instead of letting them free up the pod through companionship.',
    costText: '300 WP',
    wpCost: 300,
    requirementsText: 'Requires Pod Rack.',
    requiresOptionIds: ['pod-rack'],
    discountGroupId: 'pod-rack',
  }),
  option({
    id: 'one-art-please',
    page: 40,
    title: 'One Art Please',
    kind: 'counter',
    description: 'Authentic copies of mundane real-world art up to monumental size.',
    costText: '10 WP or 50 CP each',
    wpCost: 10,
    cpCost: 50,
    unitLabel: 'artworks',
    cpUnitLabel: 'CP artworks',
  }),
  option({
    id: 'its-a-small-multiverse',
    page: 41,
    title: 'It’s a Small Multiverse',
    kind: 'toggle',
    description: 'Import companions as native analogues of themselves for free.',
    costText: '100 WP',
    wpCost: 100,
  }),
  option({
    id: 'my-school',
    page: 41,
    title: 'My School',
    kind: 'toggle',
    description: 'Import companions into school settings as students or teachers without free CP.',
    costText: '30 WP',
    wpCost: 30,
  }),
  option({
    id: 'my-harem',
    page: 42,
    title: 'My Harem',
    kind: 'toggle',
    description: 'Block lovers, spouses, or children into grouped companion-slot imports.',
    costText: '300 WP',
    wpCost: 300,
    requirementsText: 'Requires Seraglio-A-Gogo.',
    requiresOptionIds: ['seraglio-a-gogo'],
  }),
  option({
    id: 'my-family',
    page: 42,
    title: 'My Family',
    kind: 'toggle',
    description: 'Import chosen relatives into jumps as your in-setting family without extra CP.',
    costText: '100 WP',
    wpCost: 100,
  }),
  option({
    id: 'many-happy-returns',
    page: 43,
    title: 'Many Happy Returns',
    kind: 'toggle',
    description: 'Earn return credits that buy ten-year revisits to previous worlds.',
    costText: '200 WP',
    wpCost: 200,
    discountGroupId: 'returns-suite',
    discountGroupLabel: 'Many Happy Returns',
  }),
  option({
    id: 'more-happy-more-returns',
    page: 43,
    title: 'More Happy, More Returns',
    kind: 'counter',
    description: 'Reduce the wait between earned return credits and then start adding extra credits.',
    costText: '50 WP each',
    wpCost: 50,
    unitLabel: 'return upgrades',
    requirementsText: 'Requires Many Happy Returns.',
    requiresOptionIds: ['many-happy-returns'],
    discountGroupId: 'returns-suite',
  }),
  option({
    id: 'macro-happy-micro-returns',
    page: 43,
    title: 'Macro Happy, Micro Returns',
    kind: 'toggle',
    description: 'Split return credits into one-year or one-month fragments.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires Many Happy Returns.',
    requiresOptionIds: ['many-happy-returns'],
    discountGroupId: 'returns-suite',
  }),
  option({
    id: 'flex-happy-flex-returns',
    page: 43,
    title: 'Flex Happy, Flex Returns',
    kind: 'toggle',
    description: 'Spend return credits in batches or mid-jump rather than only at jump boundaries.',
    costText: '100 WP',
    wpCost: 100,
    requirementsText: 'Requires Many Happy Returns.',
    requiresOptionIds: ['many-happy-returns'],
    discountGroupId: 'returns-suite',
  }),
  option({
    id: 'eye-spy',
    page: 44,
    title: 'Eye Spy',
    kind: 'toggle',
    description: 'See or sense anything happening in the Personal Reality, with keyholder blackout zones.',
    costText: '100 WP',
    wpCost: 100,
    discountGroupId: 'recording-suite',
    discountGroupLabel: 'Recording Suite',
  }),
  option({
    id: 'jump-recording',
    page: 44,
    title: 'Jump Recording',
    kind: 'toggle',
    description: 'Invisible all-sense cameras record and edit your jumps and Personal Reality activity.',
    costText: '200 WP or Free with Big Benefactor',
    wpCost: 200,
    discountGroupId: 'recording-suite',
  }),
  option({
    id: 'semi-euclidean',
    page: 44,
    title: 'Semi-Euclidean',
    kind: 'toggle',
    description: 'Safe, cosmetic-but-strange geometry that makes the reality feel larger and odder.',
    costText: '50 WP',
    wpCost: 50,
    discountGroupId: 'geometry-suite',
    discountGroupLabel: 'Geometry Suite',
  }),
  option({
    id: 'non-euclidean',
    page: 44,
    title: 'Non-Euclidean',
    kind: 'variant',
    description: 'Full Cthulhu-grade geometry distortion with limited or full immunity for you and companions.',
    costText: '100 WP or 200 WP',
    requirementsText: 'Requires Semi-Euclidean.',
    requiresOptionIds: ['semi-euclidean'],
    discountGroupId: 'geometry-suite',
    variants: [
      {
        id: 'limited-immunity',
        label: 'Limited Immunity',
        costText: '100 WP',
        wpCost: 100,
        summary: 'You and fiat-backed companions resist most of the geometry shock.',
      },
      {
        id: 'full-immunity',
        label: 'Full Immunity',
        costText: '200 WP',
        wpCost: 200,
        summary: 'Buy full immunity for yourself and fiat-backed companions.',
      },
    ],
  }),
  option({
    id: 'all-your-stuff',
    page: 45,
    title: 'All Your Stuff',
    kind: 'toggle',
    description: 'Bring the nonliving property you personally owned before chain start and fiat-back it.',
    costText: '100 WP',
    wpCost: 100,
  }),
  option({
    id: 'all-your-pets',
    page: 45,
    title: 'All Your Pets',
    kind: 'toggle',
    description: 'Bring owned or family-owned animals, restore pre-chain deaths, and keep them healthy.',
    costText: 'Free with All Your Stuff',
    wpCost: 0,
    optionalFree: true,
    requirementsText: 'Requires All Your Stuff.',
    requiresOptionIds: ['all-your-stuff'],
  }),
  option({
    id: 'companions-stuff',
    page: 45,
    title: 'Companion’s Stuff',
    kind: 'toggle',
    description: 'A special companion-only drawback track for mirroring All Your Stuff and All Your Pets.',
    costText: 'Special',
    wpCost: 0,
    optionalFree: true,
  }),
  option({
    id: 'all-your-peeps',
    page: 46,
    title: 'All Your Peeps',
    kind: 'variant',
    description: 'Recruit pre-jump friends with limited-time sincerity windows or buy an unlimited plan.',
    costText: '50 WP each or 600 WP unlimited',
    variants: [
      {
        id: 'attempt-packs',
        label: 'Attempt Packs',
        costText: '50 WP each',
        wpCost: 50,
        summary: 'Buy individual three-strike invite attempts.',
      },
      {
        id: 'unlimited-plan',
        label: 'Unlimited Plan',
        costText: '600 WP',
        wpCost: 600,
        summary: 'Unlimited recruitments, with paid re-tries still costing 50 WP each.',
      },
    ],
  }),
  option({
    id: 'personal-realty',
    page: 46,
    title: 'Personal Realty',
    kind: 'counter',
    description: 'Upgrade the Personal Reality into a copied home galaxy or later visited galaxies.',
    costText: '3000 WP, additional purchases allowed',
    wpCost: 3000,
    unitLabel: 'galaxy copies',
    discountGroupId: 'personal-realty-group',
    discountGroupLabel: 'Personal Realty',
  }),
  option({
    id: 'personal-mini-realty',
    page: 46,
    title: 'Personal Mini-Realty',
    kind: 'toggle',
    description: 'Start with a copied home solar system instead of a full galaxy.',
    costText: '500 WP',
    wpCost: 500,
    discountGroupId: 'personal-realty-group',
  }),
  option({
    id: 'shell-by-dyson',
    page: 47,
    title: 'Shell By Dyson',
    kind: 'toggle',
    description: 'Convert the mini-reality solar system into a one-AU Dyson shell.',
    costText: '500 WP',
    wpCost: 500,
    requirementsText: 'Requires Personal Mini-Reality.',
    requiresOptionIds: ['personal-mini-realty'],
    discountGroupId: 'personal-realty-group',
  }),
  option({
    id: 'he-abides',
    page: 48,
    title: 'He Abides',
    kind: 'limitation',
    description: 'An unavoidable freeloader lives in your Personal Reality.',
    costText: '+10 WP',
    wpGain: 10,
  }),
  option({
    id: 'astor-and-hilton',
    page: 48,
    title: 'Astor & Hilton',
    kind: 'limitation',
    description: 'Heckling balcony puppets mock failures and missteps.',
    costText: '+20 WP',
    wpGain: 20,
  }),
  option({
    id: 'weregild',
    page: 48,
    title: 'Weregild',
    kind: 'limitation',
    description: 'Every entry attempt requires a fresh toll of intrinsically valuable goods.',
    costText: '+50 WP',
    wpGain: 50,
  }),
  option({
    id: 'bat-cave',
    page: 48,
    title: 'Bat Cave',
    kind: 'limitation',
    description: 'The reality becomes a bat cave, though the bats remain unusually tidy.',
    costText: '+50 WP',
    wpGain: 50,
  }),
  option({
    id: 'real-bat-cave',
    page: 48,
    title: 'Real Bat Cave',
    kind: 'limitation',
    description: 'Replace tidy bats with guano everywhere.',
    costText: '+150 WP',
    wpGain: 150,
  }),
  option({
    id: 'crowd-scene',
    page: 49,
    title: 'Crowd Scene',
    kind: 'limitation',
    description: 'Public areas are crowded with harmless but obstructive faceless strangers.',
    costText: '+50 WP',
    wpGain: 50,
  }),
  option({
    id: 'fluorescent-lighting',
    page: 49,
    title: 'Fluorescent Lighting',
    kind: 'limitation',
    description: 'Your lighting and personal devices become visibly and physically worse.',
    costText: '+100 WP',
    wpGain: 100,
  }),
  option({
    id: 'lost-and-found-section',
    page: 49,
    title: 'Lost and Found Section',
    kind: 'limitation',
    description: 'Misplaced junk from visited worlds accumulates unpredictably in the Personal Reality.',
    costText: '+100 WP',
    wpGain: 100,
  }),
  option({
    id: 'zero-time',
    page: 49,
    title: 'Zero Time',
    kind: 'limitation',
    description: 'Lose all between-jump downtime.',
    costText: '+100 WP',
    wpGain: 100,
  }),
  option({
    id: 'warehouse-funk',
    page: 49,
    title: 'Warehouse Funk',
    kind: 'limitation',
    description: 'The Personal Reality stops perfectly odor-scrubbing itself.',
    costText: '+100 WP',
    wpGain: 100,
  }),
  option({
    id: 'whorehouse',
    page: 49,
    title: 'Whorehouse',
    kind: 'limitation',
    description: 'Everything acquires tacky, lewd design cues.',
    costText: '+100 WP',
    wpGain: 100,
  }),
  option({
    id: 'dangerous-wildlife',
    page: 49,
    title: 'Dangerous Wildlife',
    kind: 'limitation',
    description: 'The Personal Reality’s wildlife becomes openly hostile.',
    costText: '+100 WP',
    wpGain: 100,
    requirementsText: 'Requires Wildlife for Your Wild Life.',
    requiresOptionIds: ['wildlife-for-your-wild-life'],
  }),
  option({
    id: 'infestation',
    page: 50,
    title: 'Infestation',
    kind: 'limitation',
    description: 'Pests and vermin constantly re-establish themselves unless you clean manually.',
    costText: '+100 WP',
    wpGain: 100,
  }),
  option({
    id: 'nasty-creepy-ugh',
    page: 50,
    title: 'Nasty Creepy Ugh',
    kind: 'limitation',
    description: 'Mold, fungus, spores, and invasive growths spread through the Personal Reality.',
    costText: '+100 WP',
    wpGain: 100,
  }),
  option({
    id: 'air-fresheners-needed',
    page: 50,
    title: 'Air Fresheners Needed',
    kind: 'limitation',
    description: 'A lived-in smell builds up unless the reality is aired out or deeply cleaned.',
    costText: '+100 WP',
    wpGain: 100,
  }),
  option({
    id: 'journeying-spirits',
    page: 50,
    title: 'Journeying Spirits',
    kind: 'limitation',
    description: 'Recently dead spirits temporarily pass through and interfere with daily life.',
    costText: '+100 WP',
    wpGain: 100,
  }),
  option({
    id: 'haunted',
    page: 50,
    title: 'Haunted',
    kind: 'limitation',
    description: 'Journeying spirits stop moving on quickly and become persistent nuisances.',
    costText: '+100 WP',
    wpGain: 100,
    requirementsText: 'Requires Journeying Spirits.',
    requiresOptionIds: ['journeying-spirits'],
  }),
  option({
    id: 'ghost-town',
    page: 50,
    title: 'Ghost Town',
    kind: 'limitation',
    description: 'The Village starts as a neglected ghost town full of unease.',
    costText: '+100 WP',
    wpGain: 100,
    requirementsText: 'Requires The Village.',
    requiresOptionIds: ['the-village'],
  }),
  option({
    id: 'warehouse-clock',
    page: 51,
    title: 'Warehouse Clock',
    kind: 'variant',
    description: 'Limit how long you can spend inside the Personal Reality per day while jumping.',
    costText: '+100 WP or +200 WP',
    variants: [
      {
        id: 'one-hour',
        label: 'Level 1: One Hour',
        costText: '+100 WP',
        wpGain: 100,
        summary: 'Spend no more than one hour per day in the Personal Reality.',
      },
      {
        id: 'fifteen-minutes',
        label: 'Level 2: Fifteen Minutes',
        costText: '+200 WP',
        wpGain: 200,
        summary: 'Reduce the time limit to fifteen minutes per day.',
      },
    ],
  }),
  option({
    id: 'museum-tours',
    page: 51,
    title: 'Museum Tours',
    kind: 'limitation',
    description: 'Japaneseoid tourists appear at all hours and cannot be secured out of any zone.',
    costText: '+150 WP',
    wpGain: 150,
  }),
  option({
    id: 'interstitial-lighting',
    page: 51,
    title: 'Interstitial Lighting',
    kind: 'limitation',
    description: 'Large sections of the Personal Reality are badly lit and unreliable.',
    costText: '+200 WP',
    wpGain: 200,
  }),
  option({
    id: 'maintenance-issues',
    page: 51,
    title: 'Maintenance Issues',
    kind: 'limitation',
    description: 'All systems degrade into a constant low-level repair burden.',
    costText: '+200 WP',
    wpGain: 200,
    requirementsText: 'Requires Interstitial Lighting.',
    requiresOptionIds: ['interstitial-lighting'],
  }),
  option({
    id: 'unsecured',
    page: 51,
    title: 'Unsecured',
    kind: 'limitation',
    description: 'The Personal Reality can be breached by superhuman power or genius.',
    costText: '+200 WP',
    wpGain: 200,
  }),
  option({
    id: 'real-world-location',
    page: 51,
    title: 'Real World Location',
    kind: 'limitation',
    description: 'The Personal Reality gains a physically accessible in-setting location.',
    costText: '+200 WP',
    wpGain: 200,
    requirementsText: 'Requires Unsecured.',
    requiresOptionIds: ['unsecured'],
  }),
  option({
    id: 'uncontrolled-portal',
    page: 51,
    title: 'Uncontrolled Portal',
    kind: 'limitation',
    description: 'Legends and hidden gates to your Personal Reality spread through visited worlds.',
    costText: '+200 WP',
    wpGain: 200,
    requirementsText: 'Requires Unsecured.',
    requiresOptionIds: ['unsecured'],
  }),
  option({
    id: 'natural-disasters',
    page: 52,
    title: 'Natural Disasters',
    kind: 'limitation',
    description: 'Disasters repeatedly strike the Personal Reality during each jump.',
    costText: '+200 WP',
    wpGain: 200,
  }),
  option({
    id: 'dont-look-down',
    page: 52,
    title: 'Don’t Look Down',
    kind: 'limitation',
    description: 'Break the Personal Reality into zeppelin-suspended sections over an endless cloud sea.',
    costText: '+300 WP',
    wpGain: 300,
  }),
  option({
    id: 'the-labyrinth-of-jumpnos',
    page: 52,
    title: 'The Labyrinth of Jumpnos',
    kind: 'limitation',
    description: 'Everything exists, but in a shifting giant labyrinth.',
    costText: '+300 WP',
    wpGain: 300,
  }),
  option({
    id: 'jumpotaur',
    page: 52,
    title: 'Jumpotaur',
    kind: 'limitation',
    description: 'A powerful adaptive monster hunts inhabitants through the labyrinth passages.',
    costText: '+200 WP',
    wpGain: 200,
    requirementsText: 'Requires The Labyrinth of Jumpnos.',
    requiresOptionIds: ['the-labyrinth-of-jumpnos'],
  }),
  option({
    id: 'a-digital-frontier',
    page: 53,
    title: 'A Digital Frontier',
    kind: 'limitation',
    description: 'Your Personal Reality becomes virtual and requires special handling outside virtual worlds.',
    costText: '+100 WP',
    wpGain: 100,
  }),
  option({
    id: 'never-the-twain-shall-meet',
    page: 53,
    title: 'Never The Twain Shall Meet',
    kind: 'variant',
    description: 'Make the Personal Reality fully virtual and block physical transfers between it and reality.',
    costText: '+500 WP or +200 WP',
    variants: [
      {
        id: 'primary-or-general',
        label: 'Primary / General Use',
        costText: '+500 WP',
        wpGain: 500,
        summary: 'Apply the full drawback to a primary or general Personal Reality setup.',
      },
      {
        id: 'second-reality-only',
        label: 'Second Reality Only',
        costText: '+200 WP',
        wpGain: 200,
        summary: 'Apply the drawback only to a Second Reality and take the discount.',
      },
    ],
  }),
  option({
    id: 'big-benefactor',
    page: 53,
    title: 'Big Benefactor',
    kind: 'variant',
    description: 'Turn your chain into reality entertainment with extra demands, viewer punishments, and eviction risk.',
    costText: '+500 WP or +50 WP every jump',
    variants: [
      {
        id: 'flat-bonus',
        label: 'Flat Bonus',
        costText: '+500 WP',
        wpGain: 500,
        summary: 'Take the whole benefit up front.',
      },
      {
        id: 'per-jump',
        label: 'Per Jump Bonus',
        costText: '+50 WP per jump',
        summary: 'Gain 50 WP for each completed jump instead of a flat 500.',
      },
    ],
  }),
  option({
    id: 'the-woods-are-lovely-dark-and-deep',
    page: 53,
    title: 'The Woods Are Lovely Dark and Deep',
    kind: 'limitation',
    description: 'Put the Personal Reality in an impossible primeval forest full of unimaginable external threats.',
    costText: '+1000 WP, cannot be bought off',
    wpGain: 1000,
  }),
  option({
    id: 'renegade-ownership-of-personal-reality',
    page: 55,
    title: 'Ownership of Renegade’s Personal Reality',
    kind: 'toggle',
    description: 'Renegade supplement CP option to inherit the defeated Renegade’s Personal Reality as a second one.',
    costText: '300 CP',
    cpCost: 300,
  }),
  option({
    id: 'renegade-prisoner-pod',
    page: 55,
    title: 'Prisoner Pod',
    kind: 'toggle',
    description: 'Renegade supplement CP option for an occupied pod containing a captured prisoner.',
    costText: '300 CP',
    cpCost: 300,
  }),
];

export const personalRealityOptionsById = Object.fromEntries(
  personalRealityOptionCatalog.map((entry) => [entry.id, entry]),
) as Record<string, PersonalRealityOption>;
